### ISSUE TITLE
have a problem

### ISSUE THREAD

**Issue by SlaSerX** [skx/webmail#28]
[root☮zeus.darkshell.eu]-(~)
└> go get -u github.com/skx/webmail

# github.com/jhillyerd/enmime
go/src/github.com/jhillyerd/enmime/boundary.go:154:7: undefined: "github.com/pkg/errors".Is
┌[root☮zeus.darkshell.eu]-(~)
└> 
┌[root☮zeus.darkshell.eu]-(~)
└>  go install github.com/skx/implant/

can't load package: package github.com/skx/implant: cannot find package "github.com/skx/implant" in any of:
	/usr/lib/go-1.10/src/github.com/skx/implant 
	/root/go/src/github.com/skx/implant

**Comment by skx** [comment]
This should work, tested in fresh docker container:

```
$ export GO111MODULE=on
$ go get -u github.com/skx/implant
$  ls -l $(which implant)
-rwxr-xr-x 1 root root 4049105 Nov 27 19:30 /go/bin/implant

```

```
$ git clone git@github.com:skx/webmail.git
$ cd webmail/
$ go generate
$ go build .
```

Suboptimal, when go embed is in a released version it can be made more idiomatic.

**Comment by SlaSerX** [comment]
thx
